/*
 * SutraLang v3 Core - Self-Hosting ARM64 Code Generator
 * Generates native ARM64 assembly with SutraOS State Machine action dispatch.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "sutra_codegen_arm64.h"

int sutra_codegen_arm64_emit(const SutraIrStream *ir_stream, const char *output_assembly_path) {
    FILE *out = fopen(output_assembly_path, "w");
    if (!out) return -1;

    fprintf(out, "// Generated by SutraLang v3 Core (SutraOS Sovereign Native Generator)\n");
    fprintf(out, ".section .rodata\n");

    // Collect string literals
    for (int i = 0; i < ir_stream->count; i++) {
        const SutraIrInstruction *inst = &ir_stream->instructions[i];
        if (inst->opcode == IR_STORE && inst->arg2[0] != '\0') {
            fprintf(out, ".Lstr_%s:\n", inst->arg1);
            fprintf(out, "    .string \"%s\\n\"\n", inst->arg2);
            fprintf(out, "    .set .Lstr_len_%s, . - .Lstr_%s\n", inst->arg1, inst->arg1);
        }
    }

    fprintf(out, "\n.text\n");
    fprintf(out, ".global main\n");
    fprintf(out, ".type main, %%function\n");
    fprintf(out, "main:\n");
    fprintf(out, "    stp x29, x30, [sp, #-16]!\n");
    fprintf(out, "    mov x29, sp\n\n");
    fprintf(out, "    // Initialize SutraOS Zero-GC Runtime\n");
    fprintf(out, "    bl sutra_os_runtime_init\n\n");

    int is_sutraos = 0;

    for (int i = 0; i < ir_stream->count; i++) {
        const SutraIrInstruction *inst = &ir_stream->instructions[i];

        switch (inst->opcode) {
            case IR_ALLOC:
                fprintf(out, "    // IR_ALLOC: %s\n", inst->arg1);
                break;

            case IR_STORE:
                fprintf(out, "    // IR_STORE: %s = \"%s\"\n", inst->arg1, inst->arg2);
                break;

            case IR_CALL:
                if (strcmp(inst->arg2, "Print") == 0) {
                    fprintf(out, "    // IR_CALL Print (%s)\n", inst->arg1);
                    fprintf(out, "    mov x0, #1\n"); // stdout
                    fprintf(out, "    adrp x1, .Lstr_%s\n", inst->arg1);
                    fprintf(out, "    add x1, x1, :lo12:.Lstr_%s\n", inst->arg1);
                    fprintf(out, "    mov x2, .Lstr_len_%s\n", inst->arg1);
                    fprintf(out, "    mov x8, #64\n"); // sys_write
                    fprintf(out, "    svc #0\n\n");
                } else {
                    fprintf(out, "    // IR_CALL SutraOS Action: %s (%s)\n", inst->arg2, inst->arg1);
                    fprintf(out, "    bl sutra_os_action_%s\n\n", inst->arg2);
                    is_sutraos = 1;
                }
                break;

            case IR_SMRITI:
                fprintf(out, "    // IR_SMRITI: %s\n", inst->arg1);
                fprintf(out, "    bl sutra_os_action_SmritiSync\n\n");
                is_sutraos = 1;
                break;

            case IR_RET:
                if (is_sutraos) {
                    fprintf(out, "    // Run SutraOS Empirical Verification Suite\n");
                    fprintf(out, "    bl sutra_os_run_verification\n\n");
                }
                fprintf(out, "    // IR_RET\n");
                fprintf(out, "    mov x0, #0\n");
                fprintf(out, "    ldp x29, x30, [sp], #16\n");
                fprintf(out, "    ret\n");
                break;
        }
    }

    fclose(out);
    return 0;
}
